### ISSUE TITLE
Example Server

### ISSUE THREAD

**Issue by bsmelo** [ARMmbed/java-coap#15]
Hello,

I see there is an `example client` application included. Is there an `example server` as well? I couldn't find any. If you guys actually have one but it's not available in the repository for any reason, could I have it in a gist file or something like that?

Thanks!
Bruno Melo.

**Comment by szysas** [comment]
some simple example could be (using coap over tcp):

```
     CoapTransport coapTransport = new SocketServerTransport(port, true);

        emulatorServer = CoapServerBuilder.newBuilderForTcp()
                .transport(coapTransport)
                .blockSize(BlockSize.S_1024_BERT)
                .maxIncomingBlockTransferSize(101_000)
                .maxMessageSize(20_000)
                .build()
                .start();


        //read only resources
        emulatorServer.addRequestHandler("/small-1k", new ReadOnlyCoapResource(text5k.substring(0, 1000)));
        emulatorServer.addRequestHandler("/large-10k", new ReadOnlyCoapResource((text5k + text5k).substring(0, 10000)));

        emulatorServer.addRequestHandler("/write", new CoapResource() {
            @Override
            public void get(CoapExchange exchange) {
                exchange.setResponseCode(Code.C405_METHOD_NOT_ALLOWED);
                exchange.sendResponse();
            }

            @Override
            public void put(CoapExchange exchange) {
                exchange.setResponseCode(Code.C204_CHANGED);
                exchange.setResponseBody(Integer.valueOf(exchange.getRequestBody().length).toString());
                exchange.sendResponse();
            }
        });
```

**Comment by bsmelo** [comment]
Thanks a lot!

For anyone who might end up here with the same question, I've made an `example-server` application, based on the code provided above by @szysas, with a few modification to include a `.well-known/core` resource and an observable resource as well, so basic functionality from these RFCs can be seen as well.
It is available at https://github.com/bsmelo/java-coap/commit/52a9b806297019f02f90f1478b5da31966491c3f

Thanks again,
Bruno Melo.
