### ISSUE TITLE
[Potential] Security Vulnerabilities within java-coap

### ISSUE THREAD

**Issue by bsmelo** [ARMmbed/java-coap#16]
Hello developers of java-coap,

My name is Bruno, and I'm an MSc. student in Brazil within the Institute of Computing from the University of Campinas.
As part of my research on the application of fuzzing techniques for robustness and security black-box testing of CoAP implementations, I've tested your library. The sample used in my research was compiled from distribution/commit 23e62f3 @ 2018-03-21. The application used to test it was https://github.com/bsmelo/java-coap/commit/52a9b806297019f02f90f1478b5da31966491c3f.

I'm contacting you because the application mentioned above was one of the samples for which our tool was able to detect robustness and/or security issues. In a broad sense, every failure we found can actually be classified as a security vulnerability, because they impact availability --- the application either aborts or needs forceful restart in order to restore servicing CoAP requests. However, we didn't go as far as performing a thorough root-cause analysis for those failures, since it would be unfeasible for us (more than 100 failures were detected across 25 samples, each one using a different CoAP library, spanning 8 programming languages) and thus out-of-scope of this particular research.

We think that one of our main contributions is the opportunity to make a real-world impact on IoT security by reporting those failures to CoAP libraries' maintainers, with a comprehensible and easy way to replicate them so developers can further investigate and fix those failures. So, in order to follow up with a responsible disclosure process, we ask for a proper e-mail address (or any other form of contact) so we can send you:
- A script to reproduce the failures;
- A pcap file used by the script, containing the packets causing the failures;
- A logfile with the stacktraces we got for each reported failure.

We expect a reply anytime soon.
Please let us know if which form of contact should we use --- or if it's ok to use this channel.

Thanks & Regards,
Bruno Melo.

**Comment by szysas** [comment]
Hi, thanks for your message. I'm very interested to see your results, I think we can use this channel for conversation. If you want email contact, mine is: szymon.sasin@arm.com.

**Comment by bsmelo** [comment]
Please let us know if you were able to reproduce it and/or if further support is needed for that.

**Comment by szysas** [comment]
Thanks a lot! I will look at it.

**Comment by szysas** [comment]
For the record, I will copy paste here your script:
```python
# Start SUT before running this script
from scapy.all import *

# To send through lo interface
conf.L3socket = L3RawSocket

DST_IP = "127.0.0.1"
DST_PORT = 5683
SRC_PORT = 5000
VERBOSE = 0
TIMEOUT = 2

def reproduce_failure():
    raw_input("Reproduce Failure #%d?" % FAILURE_ID)
    for i in xrange(0, PKTS):
        resp = sr1(IP(dst=DST_IP)/UDP(sport=SRC_PORT, dport=DST_PORT)/packets[FAILURE_ID+i].load, verbose=VERBOSE, timeout=TIMEOUT)
    # Restart SUT at this point, so the next failure can be reproduced

# Read packets from pcap file
packets = rdpcap('java-coap-reproduced.pcapng')

PKTS = 1
# Failure: ?		Illegal observer argument
FAILURE_ID = 0
reproduce_failure()

# Failure: CoapPacket.java	360	Wrong TOKEN value, size should be within range 0-8 (java.lang.IllegalArgumentException)
FAILURE_ID = 1
reproduce_failure()

# Failure: ?		null
FAILURE_ID = 2
reproduce_failure()

# Failure: ?		invalid messageid, should be within range 0-65535
FAILURE_ID = 3
reproduce_failure()
```

**Comment by bsmelo** [comment]
No problem.

This case is a particular one, since for most of our target implementations we use a sample server application commonly provided by the library developers themselves. Since this library distribution doesn't include a basic server application, it was the only one we had to develop the sample ourselves. This is what I did guided by you in https://github.com/ARMmbed/java-coap/issues/15.

That said, if you want to safeguard and paste the server app source code here as well---since you'll probably need to run it as well to reproduce the issues---, feel free to do that. :)

**Comment by szysas** [comment]
This commit https://github.com/ARMmbed/java-coap/commit/51f9ae316c76baac805681a013f050394a957dce fixes those issue. 
Could you rerun your tests and if things are OK close, this ticket?

**Comment by bsmelo** [comment]
How can I integrate your new commit with my own fork that has the example-server app?
I've tried `git pull https://github.com/ARMmbed/java-coap.git master` which seemed to work since it gives me the following on `git log`:
```
commit 66db40a3b0c3760726b81f3c37e69c4b59bc4399
Merge: 52a9b80 51f9ae3
Author: Bruno Melo <bsilva.melo@gmail.com>
Date:   Wed Apr 11 14:20:50 2018 -0300

    Merge branch 'master' of https://github.com/ARMmbed/java-coap

commit 51f9ae316c76baac805681a013f050394a957dce
Author: Szymon Sasin <szymon.sasin@arm.com>
Date:   Wed Apr 11 10:21:32 2018 +0300

    #16 handle malformed coap messages

commit ca36140f563393a69dd883084a0d7556f5480598
Author: Szymon Sasin <szymon.sasin@arm.com>
Date:   Wed Mar 28 14:47:32 2018 +0300

    [DEVELOP] 5.1.0-SNAPSHOT

commit 6a54940040aaad69e705b3336dad3a0902e01a0e
Author: Szymon Sasin <szymon.sasin@arm.com>
Date:   Wed Mar 28 14:47:29 2018 +0300

    [RELEASE] 5.0.0

commit 52a9b806297019f02f90f1478b5da31966491c3f
Author: Bruno Melo <bsilva.melo@gmail.com>
Date:   Thu Mar 22 15:27:37 2018 -0300

    Added example-server application

commit 23e62f33b53d7330076b9eb04ca99fa81bfef5c4
Author: Szymon Sasin <szymon.sasin@arm.com>
Date:   Wed Mar 21 15:41:02 2018 +0200

    fix: support 7.01 CSM without any options
```

But somehow it doesn't look like your new commits are effective:
```
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
/opt/apache-maven-3.3.9/bin/mvn clean install -DskipTests
cd example-server
<changed parent:version to 5.1.0-SNAPSHOT in example-server/pom.xml>
 $ ./run.sh         
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building example-server 5.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ example-server ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ example-server ---
[WARNING] 
java.lang.UnsupportedClassVersionError: com/mbed/coap/example/DeviceEmulator : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:270)
        at java.lang.Thread.run(Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.300 s
[INFO] Finished at: 2018-04-11T14:39:30-03:00
[INFO] Final Memory: 11M/213M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project example-server: An exception occured while executing the Java class. com/mbed/coap/example/DeviceEmulator : Unsupported major.minor version 52.0 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by bsmelo** [comment]
I'm probably doing something *very* wrong, but I don't know what it is...

**Comment by szysas** [comment]
@bsmelo any luck with merging/rebasing?

**Comment by bsmelo** [comment]
Hi, sorry for this delay... I'll try again tomorrow.

**Comment by bsmelo** [comment]
No, no luck.

As you can see from my previous reply, I had already changed that version:
```
(...)
<changed parent:version to 5.1.0-SNAPSHOT in example-server/pom.xml>
(...)
```

Rebasing should also be OK, as you can see from the `git log` output in that same reply.
I don't get what might be wrong here :/
