### ISSUE TITLE
Multicast server example

### ISSUE THREAD

**Issue by xsimek20** [ARMmbed/java-coap#20]
Hi I have problem with multicast request. I create server 
```
MulticastSocketTransport transport = new MulticastSocketTransport(
                new InetSocketAddress(InetAddress.getByName("224.0.1.187"), 5683),
                "224.0.1.187",
                Executors.newScheduledThreadPool(
                        NetworkConfig.getStandard().getInt(NetworkConfig.Keys.PROTOCOL_STAGE_THREAD_COUNT), 
                        new NamedThreadFactory("CoapServer#")));

        server = CoapServer.builder().transport(transport).build();
        server.addRequestHandler("/cit/s", new SimpleCoapResource());
        server.start();
```
but every multicast request faild with error message "c.m.coap.server.internal.CoapMessaging   : Can not process CoAP message ..."

Can you give me some hint what I do wrong or working example?

thank you for answering my question

**Comment by szysas** [comment]
What kind of coap message are you sending? This error message might mean, that there was no request. Can you provide logs are this error?

**Comment by xsimek20** [comment]
It's multicast message without method type (POST, GET, PUT...) and that is reason why I get this error
