### ISSUE TITLE
Difference with californium project ?

### ISSUE THREAD

**Issue by sbernard31** [ARMmbed/java-coap#26]
Hi guys,
   I just discover your project and It seems pretty similar to [Californium](https://github.com/eclipse/californium/) project, I mean this is a Java SE implementation of CoAP.
   So my naïve question is : what are the differences ?  why creating another java project ?
Thx :pray:

**Comment by szysas** [comment]
Hi, I'm not familiar with californium project so I don't know differences, I'm not sure if anyone did any comparison. This project has been created quite long time ago, way before CoAP became RFC standard.

**Comment by sbernard31** [comment]
OK so this project was not created because of known limitation of Californium.

Thx for your prompt answer :pray:
