### ISSUE TITLE
Bound to other IP-Addresses

### ISSUE THREAD

**Issue by irinil** [ARMmbed/java-coap#28]
Hello,

I created a new method for the server. With this method you can bind other ip addresses in the same network and not only with localhost.

`  public CoapServerBuilderForUdp transport(InetAddress address,int port) {
            transport(new DatagramSocketTransport(new InetSocketAddress(address,port)));
            return this;
        }`

If you find it useful I can make a pull request. If this feature exists already (for example with the CoapTransport) and you think is not necessary please let me know!

Thank you for your time!

**Comment by szysas** [comment]
Hi @irinil, 
If you feel that it's needed, please make a pull request.
(Sorry for late reply)
