### ISSUE TITLE
Notifying LWM2M server periodically with data from client

### ISSUE THREAD

**Issue by Karandev** [ARMmbed/java-coap#6]
How do we update the LWM2M server about a change in some sensor value, for example temperature value obtained from device sensors, in the form of endpoints and resources?

**Comment by szysas** [comment]
There are two things:
1. Make a resource to be observable (for example https://github.com/ARMmbed/java-coap/blob/master/coap-core/src/test/java/com/mbed/coap/observe/SimpleObservableResourceTest.java#L52)

2. Subscribe to a resource from RestAPI: https://docs.mbed.com/docs/mbed-device-connector-web-interfaces/en/latest/api-reference/

**Comment by Karandev** [comment]
1. How to pass value to the observable resource?

**Comment by Karandev** [comment]
If the value of an observable resource changed from client and then we need to push that new value to mbed server what should be done? This we are trying to do once we receive sensor data after a period of every 15 seconds.
We are using like this:
`if(startedCoapServer != null && registrationManager != null) {
                SimpleObservableResource obsResourceX = new SimpleObservableResource("/AndroidDevice/Gravity/X", startedCoapServer);
                try {
                    obsResourceX.setBody(gravityData[0] + "");
                } catch (CoapException e) {
                    e.printStackTrace();
                }
                SimpleObservableResource obsResourceY = new SimpleObservableResource("/AndroidDevice/Gravity/Y", startedCoapServer);
                try {
                    obsResourceY.setBody(gravityData[1] + "");
                } catch (CoapException e) {
                    e.printStackTrace();
                }
                SimpleObservableResource obsResourceZ = new SimpleObservableResource("/AndroidDevice/Gravity/Z", startedCoapServer);
                try {
                    obsResourceZ.setBody(gravityData[2] + "");
                } catch (CoapException e) {
                    e.printStackTrace();
                }
                startedCoapServer.addRequestHandler("/AndroidDevice/Gravity/X", obsResourceX);
                startedCoapServer.addRequestHandler("/AndroidDevice/Gravity/Y", obsResourceY);
                startedCoapServer.addRequestHandler("/AndroidDevice/Gravity/Z", obsResourceZ);
                registrationManager.register();
            }`
This don't seems to be correct. Please help.

**Comment by szysas** [comment]
What kind of problems do you get?

**Comment by Karandev** [comment]
After some time keeping the application idle, a 502 error is received.

**Comment by szysas** [comment]
Logs please.

**Comment by szysas** [comment]
Note also that I added observable resource to example-client: https://github.com/ARMmbed/java-coap/blob/dev/example-client/example-client/src/main/java/com/mbed/coap/example/DeviceEmulator.java#L85

**Comment by Karandev** [comment]
We are able to send data continously every 15 seconds. Is there any parameter we need to set so that this happens for atleast, let's say, 30 minutes or one hour, without any interruption?

**Comment by szysas** [comment]
Well, just set your scheduler to send notification as often as you need.

**Comment by Karandev** [comment]
We keep on sending the data every 15 sec. After about 10 minutes or so testing in the mbed server console, clicking the Test Api button keeps on trying to fetch the data for get resources, but with no result.
What could be wrong?

**Comment by szysas** [comment]
Could you attached device logs?

**Comment by szysas** [comment]
I'm sure there is a way to make a (bash) script that would do the job automatically. Any collaboration is more than welcome :).
Is original issue solved? If so could we close this ticket?
